version: 1

package:
  id:
  name:
  language:
  type:

metadata:
  aliases: []
  tags: []

repositories:
  - owner:
    repo:

    kind:

    stack: []

    tags: []

    official: false

    priority: 50

    notes:
